name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.gemfile }} enforce safer methods ${{ matrix.enforce_safer_methods }}
    strategy:
      matrix:
        ruby: [ "3.3", "3.2", "3.1" ]
        gemfile: [ "activerecord_72.gemfile", "activerecord_71.gemfile", "activerecord_70.gemfile", "activerecord_61.gemfile" ]
        enforce_safer_methods: [ "true", "false" ]

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
      env:
        ENFORCE_SAFER_METHODS: ${{ matrix.enforce_safer_methods  }}
